version: '3.8'

services:
  backend:
    build: ./backend
    container_name: backend
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - app_network

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "5000:8080"
    depends_on:
      - backend
    networks:
      - app_network

  db:
    image: postgres:13
    container_name: db
    volumes:
      - ./db:/var/lib/postgresql/data
    env_file:
      - ./backend/.env
    ports:
      - "5432:5432"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
